import crypto from "node:crypto";
import { Router } from "express";
import { decryptSecret } from "../../lib/crypto.js";
import { logger } from "../../lib/logger.js";
import { prisma } from "../../lib/prisma.js";
import { delhiveryConnector, type DelhiveryCredentials } from "../../modules/connectors/delhivery/index.js";
import { toConnectorContext } from "../../modules/connectors/types.js";

export const delhiveryWebhookRouter = Router();

function timingSafeStringEqual(a: string, b: string): boolean {
  const aBuf = Buffer.from(a);
  const bBuf = Buffer.from(b);
  return aBuf.length === bBuf.length && crypto.timingSafeEqual(aBuf, bBuf);
}

// Delhivery's push webhook has no signature or shared-header scheme at all
// (confirmed against their own docs before building this — unlike Shopify's
// HMAC, Razorpay's HMAC, or even Shiprocket's shared-header value). The only
// verification available is that the URL itself is unguessable: the token
// lives in the path, generated by us at connect-time and handed to
// Delhivery's onboarding team as "the endpoint to push scans to" (see
// routes/connections/delhivery.ts). Still a linear scan across active
// Delhivery connections to find the matching one, same MVP-scale caveat as
// Razorpay/Shiprocket's webhook routes.
delhiveryWebhookRouter.post("/:webhookToken", async (req, res) => {
  const rawBody = req.body as Buffer;
  const { webhookToken } = req.params;

  const candidates = await prisma.connection.findMany({
    where: { provider: "DELHIVERY", status: "ACTIVE" },
  });

  const connection = candidates.find((c) => {
    try {
      const creds = JSON.parse(decryptSecret(c.credentialsRef)) as DelhiveryCredentials;
      return timingSafeStringEqual(webhookToken, creds.webhookToken);
    } catch {
      return false;
    }
  });

  if (!connection) {
    res.status(401).json({ error: "invalid_token" });
    return;
  }

  let payload: { Shipment?: unknown };
  try {
    payload = JSON.parse(rawBody.toString("utf8"));
  } catch {
    res.status(400).json({ error: "invalid_json" });
    return;
  }

  if (!payload.Shipment) {
    // Acknowledge anything we don't recognize rather than erroring.
    res.json({ received: true });
    return;
  }

  try {
    await delhiveryConnector.processEvent(toConnectorContext(connection), payload.Shipment, "shipment.webhook");
  } catch (err) {
    logger.error({ err }, "delhivery_webhook_processing_failed");
    // Idempotent (Shipment upsert keyed on AWB), safe to let Delhivery retry.
    res.status(500).json({ error: "processing_failed" });
    return;
  }

  res.json({ received: true });
});
